Карточка мероприятия, шеринг, логин и регистрация
mihaillatyshov/homework-1-autumn-2023 pull request #2
Opened 2023-09-24 08:34 UTC by reddiridabl666

2023-09-26 08:27 UTC, Rioskill requested changes

2023-09-26 08:27 UTC, Rioskill commented on Wild_Spirits.md
> +- ${\color{red}При\space нажатии\space на\space логотип\space Telegram\space открывается\space t.me/share,\space кнопка\space share\space ничего\space не\space делает.}$ Если поставить десктопное при
Формулировка неудачная. Выглядит так, будто открытие t.me/share - это баг

2023-09-26 08:27 UTC, Rioskill commented on Wild_Spirits.md
> +- Ссылка отображается без какого-либо оформления. При нажатии на ссылку открывается ожидаемая страница мероприятия
Что за ссылка? Не должно ли данное замечание быть красным?

2023-09-26 08:27 UTC, Rioskill commented on Wild_Spirits.md
> +- ${\color{red}При\space нажатии\space на\space кнопку\space приглашения\space не\space происходит\space отлика\space для\space пользователя\space - непонятно,\space отправилось\space ли\space пригла
"отлик" - опечатка

2023-10-01 17:39 UTC, CyTb-On-Fire commented on Wild_Spirits.md
> +## Форма входа
Не описано поведение модального окна при обновлении страницы

2023-10-01 17:39 UTC, CyTb-On-Fire commented on Wild_Spirits.md
> +## Модальное окно уведомлений
Так же нет ничего про поведение модалки при обновлении страницы

2023-10-06 17:21 UTC, mihaillatyshov approved these changes

2023-10-07 14:55 UTC, CyTb-On-Fire approved these changes

2023-10-07 14:55 UTC, Rioskill approved these changes

2023-10-07 15:13 UTC, merged